Create `redo what_predefined`
lasp/adamant pull request #38
Opened 2024-05-21 17:58 UTC by MyApaulogies

Create the redo command `redo what_predefined`, which displays the commands listed in `redo what` which will always be listed regardless of the subdirectory of the project you're in.

2024-05-23 17:58 UTC, MyApaulogies commented
Everything should be good. There are a few edge cases, like `cd`ing into a `build` directory still brings up completions, and trying to complete `redo ../adamant` while in `~/adamant` doesn't work, and also it's a bit slower than it could be (rewrite it in Rust?) It seems usable now though, if someone wants to test it out.

2024-05-24 18:09 UTC, MyApaulogies commented
Looks like all the failing tests are typos in files I didn't change...

2024-05-30 23:43 UTC, MyApaulogies commented
> [dinkelk](https://github.com/dinkelk) and others added 18 commits May 30, 2024 23:26
Umm, any idea what happened here? In any case, I cleaned up my commit history, so it should be ready for a merge if you think it's good.

2024-05-31 15:45 UTC, Jbsco commented
Try using `rebase -i -r HEAD~#` to drop commits not authored in this PR, then rebasing on main, then again with `--committer-date-is-author-date` to restore inline commit dates. There may be other ways to do this, but should work.

2024-05-31 16:40 UTC, Jbsco approved these changes
`rebase -i -r` and drop of commits not authored in this PR seems to have done the trick!

2024-05-31 17:08 UTC, dinkelk requested changes
I think some cleanup needs to happen in env/redo_completion.sh. There is a lot of unnecessary white space and commented out code that hinders readability. The actual code looks good though.

2024-05-31 17:08 UTC, dinkelk commented on env/activate
> +. $ADAMANT_DIR/env/redo_completion.sh
Can you add a comment, so people know what this does when inspecting activate?

2024-05-31 17:08 UTC, dinkelk commented on env/activate
> +. $ADAMANT_DIR/env/redo_completion.sh
I also think this should go above line 157, ie. before the final "Done." is printed.

2024-05-31 17:08 UTC, dinkelk commented on default.do
> +        from rules.build_what_predefined import build_what_predefined as rule_cls
This change also needs to be propagated to the example project default.do as well. Can you make a PR for that over there?

2024-05-31 17:08 UTC, dinkelk commented on redo/rules/build_what_predefined.py
> +    #     return f.read().split()
Remove commented out code

2024-05-31 17:08 UTC, dinkelk commented on redo/rules/build_what_predefined.py
> +        # super(build_what_predefined, self).build(redo_1, redo_2, redo_3)
remove commented out code.

2024-05-31 17:08 UTC, dinkelk commented on env/redo_completion.sh
> +    # echo first_run = $first_run
Remove commented out code

2024-05-31 17:08 UTC, dinkelk commented on env/redo_completion.sh
> +
spacing

2024-05-31 21:35 UTC, MyApaulogies commented
Now it should be done, I took your suggestions and made a few other changes. (but the of course tests are failing for some reason...)

2024-05-31 21:42 UTC, MyApaulogies commented
It looks like they're all permissions errors... Does this have to do with changing the Dockerfile to end with `USER user` instead of `USER root`?

2024-05-31 21:50 UTC, dinkelk approved these changes

2024-05-31 23:00 UTC, merged